// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJDQcGBrcWxPL375JBrDrRQVkeLzAFRtk',
    appId: '1:816571150051:web:09e23e8b69ba84f9c09fd6',
    messagingSenderId: '816571150051',
    projectId: 'panduan-media-kreatif-islam',
    authDomain: 'panduan-media-kreatif-islam.firebaseapp.com',
    storageBucket: 'panduan-media-kreatif-islam.appspot.com',
    measurementId: 'G-4XYFE87JGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP7B0e7IWl4NjajtOrzT1cn7X9SiSNGns',
    appId: '1:816571150051:android:8581daec05d33685c09fd6',
    messagingSenderId: '816571150051',
    projectId: 'panduan-media-kreatif-islam',
    storageBucket: 'panduan-media-kreatif-islam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMr72uH38y8MDPEC3ZdAhUN0sIkaz0k9g',
    appId: '1:816571150051:ios:ea4fec8c80aab68ac09fd6',
    messagingSenderId: '816571150051',
    projectId: 'panduan-media-kreatif-islam',
    storageBucket: 'panduan-media-kreatif-islam.appspot.com',
    iosBundleId: 'com.example.pmki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMr72uH38y8MDPEC3ZdAhUN0sIkaz0k9g',
    appId: '1:816571150051:ios:5a6ef84305b738dbc09fd6',
    messagingSenderId: '816571150051',
    projectId: 'panduan-media-kreatif-islam',
    storageBucket: 'panduan-media-kreatif-islam.appspot.com',
    iosBundleId: 'com.example.pmki.RunnerTests',
  );
}
